Update Sway Apps examples to reflect changes in repo
FuelLabs/fuel-docs pull request #63
Opened 2023-01-20 05:25 UTC by mehtavishwa30

Added the following changes in the Sway Applications page:
- Changed description
- Added links to individual projects
- Added new Fractional-NFT example
- Added latest versions of forc and fuel-core being used in the apps

2023-01-24 15:13 UTC, camiinthisthang requested changes

2023-01-24 15:13 UTC, camiinthisthang commented on src/for-developers/example-contracts.md
> +> Please note all projects currently use `forc 0.32.2`, `fuel-core 0.15.1`, and `rust 1.66.0`.
where did you get these updated versions from @mehtavishwa30 ?

2023-01-24 15:19 UTC, mehtavishwa30 commented on src/for-developers/example-contracts.md
> +> Please note all projects currently use `forc 0.32.2`, `fuel-core 0.15.1`, and `rust 1.66.0`.
Got it from the official Sway Apps repo [here](https://github.com/FuelLabs/sway-applications). You can see it in the note at the end of the readme.

2023-02-16 15:33 UTC, camiinthisthang approved these changes

2023-06-20 17:14 UTC, closed without merging