minor fixes, added local node docs, syntax highlighting (JavaScript + TypeScript)
FuelLabs/fuel-docs pull request #82
Opened 2023-02-24 01:16 UTC by dabit3

- Added syntax highlighting for JS + TS
- Added local node documentation
- Fixed error in `test/harness.rs`

2023-02-24 17:02 UTC, camiinthisthang submitted a review, later dismissed
LGTM, will wait for @sarahschwartz to approve before we merge

2023-02-24 20:10 UTC, sarahschwartz requested changes
looks great, thank you! Just a note about the updates to the test harness

2023-02-24 20:10 UTC, sarahschwartz commented on beta2-quickstart-master/counter-contract/tests/harness.rs
> +    let (_instance, _id) = get_contract_instance().await;
Underscores are used for unused variables in Rust, so I think we should keep this as-is.

2023-02-24 21:00 UTC, dabit3 commented
Thanks @sarahschwartz @camiinthisthang should be gtg now :)

2023-02-27 15:14 UTC, sarahschwartz commented
@dabit3 It looks like our markdown linter failed because of these rules: no multiple consecutive blank lines, and files should end with a single newline character.

2023-02-27 16:32 UTC, dabit3 commented
Thanks @sarahschwartz I have made updates based on the linting errors, please have a look and let me know if this passes.

2023-02-27 16:35 UTC, sarahschwartz approved these changes

2023-02-27 16:41 UTC, merged