docs: quickstart fuel wallet integration
FuelLabs/fuel-docs pull request #86
Opened 2023-02-28 23:21 UTC by cold-briu

resolves #85 

This approach uses the "useFuel" and "useIsConencted" hooks from the [fuel-wallet/sdk documentation](https://wallet.fuel.network/docs/react/) and adds a third custom hook named "useWallet" the last one being added by me. 

The implementation (and the quickstart) can be cleaner by optimizing the hooks and adding them directly into the sdk. 
However that's out of this PR's scope.

2023-03-29 18:04 UTC, luizstacio requested changes
As this is, a quickstart application is good to reduce the number of files the user needs to create. It would be great to maybe create this as an advanced example, maybe something under.

Examples -> React with Hooks.

2023-03-29 18:04 UTC, luizstacio commented on beta2-quickstart-master/frontend/src/hooks/useWallet.tsx
> +const useWallet = () => {
```suggestion
export const useWallet = () => {
```

2023-03-29 18:04 UTC, luizstacio commented on beta2-quickstart-master/frontend/src/hooks/useWallet.tsx
> +			const currentAccount = await Fuel.currentAccount();
The current account can present issues if the user doesn't allow the existing account to connect. I suggest using `const [account] = await fuel.accounts()`.

2023-04-04 23:59 UTC, cold-briu commented
> As this is, a quickstart application is good to reduce the number of files the user needs to create. It would be great to maybe create this as an advanced example, maybe something under.

Hello there! 
Thanks for the feedback. 

I think the same way as you, however App component gets really complex without the hooks.
It might be better to add the hooks inside the npm package.

2023-06-12 20:25 UTC, closed without merging